### ISSUE TITLE
Does not update every minute

### ISSUE THREAD

**Issue by vinayr** [catamphetamine/react-time-ago#5] opened 2018-01-13 17:33 UTC
Something is wrong with update interval. Check the demo page - https://catamphetamine.github.io/react-time-ago/

Shows correct result for first 2 minutes. After that it takes longer time for updates. In my case it updates every 5 minutes. I'm not using `updateInterval` prop.

**Comment by catamphetamine** [comment] 2018-01-13 19:43
![image](https://user-images.githubusercontent.com/477167/34909461-86a2db20-f8b2-11e7-9d70-b0b562ec95fd.png)

![image](https://user-images.githubusercontent.com/477167/34909467-a9e765e2-f8b2-11e7-9bb2-9794e33da79f.png)

![image](https://user-images.githubusercontent.com/477167/34909471-cb1f0b0c-f8b2-11e7-8c85-c37ae82c019d.png)

![image](https://user-images.githubusercontent.com/477167/34909475-ee609630-f8b2-11e7-8944-48fd73d8424f.png)

Works for me correctly.
If you want to debug updating in your project open `node_modules/react-time-ago/modules/ReactTimeAgo.js`
https://unpkg.com/react-time-ago@1.0.11/modules/ReactTimeAgo.js

And add `console.log` to this line:
```js
// Register for the relative time autoupdate as the time goes by.
this.stop_autoupdate = window._react_time_ago_updater.add(function () {
  return _this2.forceUpdate();
});
```

**Comment by catamphetamine** [comment] 2018-01-13 19:44
Closing due to not being reproduced

**Closed by catamphetamine** 2018-01-13 19:44 UTC
